version: '3'
services:
  todotests:
    build: ./todo-app/tests/
    restart: on-failure
    depends_on:
      - todofrontend
      - todobackend
    environment:
      - FRONT_HOST=todofrontend
  todofront:
    build: ./todo-app/front-end/
    ports:
      - 3000:80
    restart: on-failure
    depends_on:
      - todobackend
    environment:
      - REACT_APP_API_HOST=todobackend
  todoback:
    build: ./todo-app/back-end/
    ports:
      - 3001:80
    restart: on-failure